kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: chat-app-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
  - containerPort: 30501
    hostPort: 5001
  - containerPort: 27017
    hostPort: 27017
